name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.in
      - name: Build
        run: |
          sphinx-apidoc -f -o docs/source/ src/
      - name: Build HTML
        run: |
          sphinx-build -b html docs/source/ docs/build/ -a
      - name: Publish on GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: docs/build
          github_token: ${{ secrets.GITHUB_TOKEN }}